version: '3'
services:
  marquez-db:
    image: postgres:14
    container_name: marquez-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=marquez
      - MARQUEZ_USER=marquez
      - MARQUEZ_PASSWORD=marquez
    ports:
      - "5432:5432"

  marquez-api:
    image: marquezproject/marquez:latest
    container_name: marquez-api
    environment:
      - MARQUEZ_CONFIG=/app/marquez.yml
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./marquez.yml:/app/marquez.yml
    links:
      - "marquez-db:postgres"
    depends_on:
      - marquez-db

  marquez-web:
    image: marquezproject/marquez-web:latest
    container_name: marquez-web
    environment:
      - MARQUEZ_HOST=marquez-api
      - MARQUEZ_PORT=5000
    ports:
      - "3000:3000"
    depends_on:
      - marquez-api

